import { motion } from 'framer-motion'
import { UploadCloud, Search, Sparkles, MessagesSquare, Zap, BrainCircuit } from 'lucide-react'

const FEATURES = [
  {
    icon: UploadCloud,
    title: 'PDF Upload',
    description: 'Drop in regulations, syllabus files, or handbooks and they’re ready to query in seconds.',
  },
  {
    icon: Search,
    title: 'Semantic Search',
    description: 'Finds the passage that means what you asked, not just the one that matches your keywords.',
  },
  {
    icon: Sparkles,
    title: 'AI-Powered Answers',
    description: 'Get a direct, written answer instead of a list of pages to read through yourself.',
  },
  {
    icon: MessagesSquare,
    title: 'Session-Based Document Chat',
    description: 'Every upload gets its own isolated session, so your documents and answers stay separate.',
  },
  {
    icon: Zap,
    title: 'Fast Retrieval',
    description: 'FAISS vector search pulls the relevant chunks back in moments, even from long documents.',
  },
  {
    icon: BrainCircuit,
    title: 'Llama 3.1 Intelligence',
    description: 'Answers are generated by Llama 3.1 8B Instruct, reasoning over exactly what you uploaded.',
  },
]

export default function Features() {
  return (
    <section id="features" className="scroll-mt-20 px-6 py-24">
      <div className="mx-auto max-w-6xl">
        <div className="max-w-xl">
          <span className="font-mono text-xs uppercase tracking-wider text-text-secondary">Capabilities</span>
          <h2 className="mt-3 font-display text-3xl font-semibold tracking-tight text-text-primary sm:text-4xl">
            Everything needed to read less and know more
          </h2>
        </div>

        <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map((feature, i) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-60px' }}
              transition={{ duration: 0.45, delay: (i % 3) * 0.08 }}
              className="group rounded-2xl border border-border bg-surface p-6 transition-shadow hover:shadow-card"
            >
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[linear-gradient(135deg,var(--color-primary),var(--color-accent))]">
                <feature.icon size={19} className="text-white" strokeWidth={2} />
              </div>
              <h3 className="mt-4 font-display text-base font-semibold text-text-primary">{feature.title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-text-secondary">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}
